#! /bin/sh


# Runs a program unless that program is already running
function conditional_run {
    local program_name=$1

    ps_result=$(ps aux \
        | grep "${program_name}" \
        | grep -v "grep" \
        | wc -l
        )
    if [ $ps_result -eq 0 ]; then
        echo "Running $program_name"
        `$program_name` &
    else
        echo "$program_name already running"
    fi
}


feh --no-fehbg --bg-fill ~/.config/bspwm/wallpaper.jpg&

xrandr --output HDMI-0 --mode 1920x1080 --pos 4520x840 --rotate normal --output DP-0 --off --output DP-1 --mode 1920x1080 --pos 3440x0 --rotate left --output DP-2 --primary --mode 3440x1440 --pos 0x480 --rotate normal --output DP-3 --off --output DP-4 --off --output DP-5 --off

xsetroot -cursor_name left_ptr


setxkbmap "ch(de)"



pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc &

bspc monitor DP-1 -d discord
bspc monitor DP-2 -d files browser steam code 6
bspc monitor HDMI-1 -d 7

bspc desktop -f browser
# move mouse to center of primary screen
xdotool mousemove 1720 1300

bspc config automatic_scheme alternate
bspc config border_width         2
bspc config window_gap          4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Vivaldi-stable desktop=browser
bspc rule -a discord desktop=discord state=fullscreen
bspc rule -a Steam desktop=steam
bspc rule -a KeePassXC state=floating

killall "compton"
compton &

killall "polybar"
polybar example &

conditional_run discord

conditional_run vivaldi-stable

killall "easyeffects"
easyeffects --gapplication-service &

conditional_run dropbox

killall "qpwgraph"
qpwgraph -ma ~/.config/qpwgraph/Patchbay.qpwgraph &

conditional_run parcellite &
